using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KUK.ChinookSync.Models.NewSchema.Mapping
{
    [Table("InvoiceLineMappings")]
    public class InvoiceLineMapping
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // Old ID is not generated by db, just moved
        public int OldInvoiceLineId { get; set; }

        [Required]
        public Guid NewInvoiceLineId { get; set; }

        [Required]
        public DateTime MappingTimestamp { get; set; }
    }
}
